server:
  port: 8082

es:
  client:
    servers: 192.168.1.113:9200

local:
  jdbc:
    url: jdbc:mysql://192.168.1.208:3306/db_search?autoReconnect=true&amp;useUnicode=true&amp;characterset=utf8mb4
    username: root
    password: 123456